### ISSUE TITLE
Register TopMed WDL Workflow at Dockstore

### ISSUE THREAD

**Issue by cricketsloan** [DataBiosphere/topmed-workflows#12]
The variant calling workflow is done, it now needs to be polished and registered at Dockstore
- [x] Build Docker image in Quay.io
- [x] Register WDL in Dockstore
- [x] Learn to create checker tool in Dockstore
- [x] Get Google bucket to use for reference files
- [x] Get consensus on which repository to use for workflow, U of Michigan, BD2K or DataBiosphere or a combination
- [x] Upload test files to FireCloud workspace

**Comment by wshands** [comment]
The first version of this workflow is registered on Dockstore at https://dockstore.org/workflows/github.com/BD2KGenomics/topmed_freeze3_calling/TopMed_Variant_Caller
