### ISSUE TITLE
Plan for the variant comparator

### ISSUE THREAD

**Issue by cricketsloan** [DataBiosphere/topmed-workflows#13]
We need to be able to compare the output of our alignment WDL with others.  This involves

1) Finding the test data
2) Find a cram or bam comparing tool
3) Determine a cut off for "good"
4) Make a plan for registering the testing with Dockstore

**Comment by wshands** [comment]
this may be the tool to use: https://genome.sph.umich.edu/wiki/BamUtil:_diff
Found at:
http://seqanswers.com/forums/showthread.php?t=5845

https://genome.sph.umich.edu/wiki/BamUtil
https://github.com/statgen/bamUtil

**Comment by wshands** [comment]
Possibly CRAM->BAM->SAM without headers and md5sum and compare md5sums

**Comment by wshands** [comment]
Jonathon at U of Michigan suggested: 
Running BWA twice on the same input isn't guaranteed to produce the same results. When reads match equally to multiple positions, the alignment is chosen randomly between those positions.

A simple sanity check is to run samtools flagstat to ensure that read counts match. The formula for calculating read count from the flagstat output is 'in total' - 'secondary' - 'supplementary'. See https://github.com/jonathonl/csg-utils/blob/master/gce/pre-align.sh#L53-L54. This of course says nothing about the quality of the alignment. For quality, we use https://github.com/statgen/qplot, but I wouldn't guarantee that the output of qplot would match exactly between two b38 crams of the same sample.

**Comment by wshands** [comment]
Also this suggestion http://deeptools.readthedocs.io/en/latest/content/tools/bamCompare.html
