### ISSUE TITLE
Error on running WDL workflow

### ISSUE THREAD

**Issue by wshands** [DataBiosphere/topmed-workflows#2]
Hi @ruchim I am attempting to run the WDL workflow with Cromwell 30.1 using the following command:
java -jar ~/.dockstore/libraries/cromwell-30.1.jar run /home/ubuntu/topmed-workflows/functional-equivalence-wdl/FunctionalEquivalence.wdl -i FunctionalEquivalence.inputs

but I am getting the following error:
[2018-02-01 01:06:50,64] [error] WorkflowManagerActor Workflow 395a0da3-6f6b-4581-92be-a85937c3d62b failed (during ExecutingWorkflowState): Evaluating size(dbSNP_vcf, "GB") failed: java.lang.IllegalArgumentException: Could not find suitable filesystem among Defaul
t to parse gs://broad-references/hg38/v0/Homo_sapiens_assembly38.dbsnp138.vcf.

Am I doing the right things to run the workflow? How do I fix the error?

Thanks

┆Issue is synchronized with this [JIRA Task](https://ucsc-cgl.atlassian.net/browse/TOP-5)
┆Issue Number: TOP-5

**Comment by ruchim** [comment]
Hey @wshands,

In case you have the hg38 reference files available to you on a local filesystem, you can either replace the GCS paths with absolute paths, or follow the instructions below to configure Cromwell to access the GCS filesystem. 

1. Authenticate to Google Cloud Platform
`gcloud auth login <google-user-id>`
2. Set your default account
`gcloud auth application-default login`
3. Configure Cromwell to use your application-default credentials.

#### cromwell.conf
```
engine {
  filesystems {
    gcs {
      auth = "application_default"
    }
  }
}

google {
  application-name = "cromwell"
  auths = [{
      name = "application_default"
      scheme = "application_default"
    }]
}
```
4. Optional: I also recommend [configuring Cromwell to use a mysql database](https://cromwell.readthedocs.io/en/develop/Configuring/#database). You can simply append the cromwell.conf file with the `database` stanza described in the documentation.

#### Modified run command
java -Dconfig.file=/path/to/cromwell.conf -jar ~/.dockstore/libraries/cromwell-30.1.jar run /home/ubuntu/topmed-workflows/functional-equivalence-wdl/FunctionalEquivalence.wdl -i FunctionalEquivalence.inputs

Hope this helps

**Comment by wshands** [comment]
Hi @ruchim,
I noticed that there is a space on line 24 of the inputs file between ...v0/ and wgs_calling_regions...
"gs://broad-references/hg38/v0/ wgs_calling_regions.hg38.interval_list"
This might be a problem?

I was unable to get the files on GCS paths to download using the WDL after following the instructions above (still seeing the same error), so I downloaded them to my host system individually, then substituted local paths, but I am seeing this error:
[ERROR] [02/05/2018 21:35:46.691] [cromwell-system-akka.dispatchers.engine-dispatcher-5] [akka://cromwell-system/user/SingleWorkflowRunnerActor/WorkflowManagerActor] WorkflowManagerActor Workflow 92c6dc66-b795-4544-a5ab-50a2b8f87e4d failed (during ExecutingWorkflowState): Job PairedEndSingleSampleWorkflow.SamToFastqAndBwaMemAndMba:0:1 exited with return code 1 which ha
s not been declared as a valid return code. See 'continueOnReturnCode' runtime attribute for more details.

How can I get more debug information?

**Comment by wshands** [comment]
Hi @ruchim, OK I found the stderr file and the issue. No need to investigate. I have to change the /usr/gitc paths.

**Comment by ruchim** [comment]
Hey @wshands ,

- Thanks for pointing that out! Fix out in a PR: https://github.com/DataBiosphere/topmed-workflows/pull/3/files Would you have review/merge privileges in this repo?

- To look at what actually failed the job and caused the job to exit with a non-zero return code, you will want to look at the stderr log file, which should be here:
cromwell-executions/PairedEndSingleSampleWorkflow/92c6dc66-b795-4544-a5ab-50a2b8f87e4d/call-SamToFastqAndBwaMemAndMba/SamToFastqAndBwaMemAndMba-stderr.log

- Would you mind posting the logs for the second attempt you made running the workflow above? It'd be good to know if I should add more instructions to the readme. 

Thank you!

**Comment by wshands** [comment]
here's the content of stderr log file:
ubuntu@ip-172-31-0-216:~/topmed-workflows/functional-equivalence-wdl$ cat /home/ubuntu/topmed-workflows/functional-equivalence-wdl/cromwell-executions/PairedEndSingleSampleWorkflow/d261ae9f-c1bd-48ab-a8e8-11653284165a/call-SamToFastqAndBwaMemAndMba/shard-0/execution/stderr
/home/ubuntu/topmed-workflows/functional-equivalence-wdl/cromwell-executions/PairedEndSingleSampleWorkflow/d261ae9f-c1bd-48ab-a8e8-11653284165a/call-SamToFastqAndBwaMemAndMba/shard-0/execution/script: line 30: /usr/gitc/bwa: No such file or directory
Error: Unable to access jarfile /usr/gitc/picard.jar
Error: Unable to access jarfile /usr/gitc/picard.jar

So its pretty clear what happened. 

It would be great if the workflow used tools in Docker containers; would you please change the workflow to use samtools, GATK, etc. from Docker containers?

**Comment by wshands** [comment]
Hi @ruchim,
I think the pipeline base recalibration step should also be using the decoy sequences: see https://github.com/CCDG/Pipeline-Standardization/blob/master/PipelineStandard.md under Reference Genome Versions

GRCh38_full_analysis_set_plus_decoy_hla.fa.fai
GRCh38_full_analysis_set_plus_decoy_hla.dict
GRCh38_full_analysis_set_plus_decoy_hla.fa

**Comment by ruchim** [comment]
@wshands Currently the workflow is already using tools from the Docker container, so as long as you're using the docker container referenced in the *.options file, you should be all set. To pass in the options file in that directory to cromwell, you'll use another arg `-o`:
`java -Dconfig.file=/path/to/cromwell.conf -jar ~/.dockstore/libraries/cromwell-30.1.jar run /home/ubuntu/topmed-workflows/functional-equivalence-wdl/FunctionalEquivalence.wdl -i FunctionalEquivalence.inputs -o FunctionalEquivalence.options`

**Comment by ruchim** [comment]
Hey @wshands,
I spoke to @eitanbanks about your question and this is my understanding:
1. The reference files used in this implementation already contain decoy sequences, feel free to check out the ref dict (gs://broad-references/hg38/v0/Homo_sapiens_assembly38.dict).
2. In this workflow, we are running the task BaseRecalibrator on all contigs in the ref dict (though in a scattered manner), thus base recalibration should already be using decoy sequences.

**Comment by eitanbanks** [comment]
And even if we aren't running BQSR on all contigs, the FE specification explicitly says that you do not need to.  It's just the autosomes that are required....

**Comment by wshands** [comment]
Thanks!

I am back to trying to run the WDL script using the Google Storage inputs. @ruchim I followed your instructions above on Google auth and created the cromwell.conf file but still see the following error:

ubuntu@ip-172-31-0-216:~/topmed-workflows/functional-equivalence-wdl$ gcloud auth login jshands@ucsc.edu
WARNING: `gcloud auth login` no longer writes application default credentials.
If you need to use ADC, see:
  gcloud auth application-default --help

You are now logged in as [jshands@ucsc.edu].
Your current project is [None].  You can change this setting by running:
  $ gcloud config set project PROJECT_ID
ubuntu@ip-172-31-0-216:~/topmed-workflows/functional-equivalence-wdl$ gcloud auth application-default login
Go to the following link in your browser:

...

Credentials saved to file: [/home/ubuntu/.config/gcloud/application_default_credentials.json]

These credentials will be used by any library that requests
Application Default Credentials.

ubuntu@ip-172-31-0-216:~/topmed-workflows/functional-equivalence-wdl$ cat /home/ubuntu/cromwell.conf
engine {
  filesystems {
    gcs {
      auth = "application_default"
    }
  }
}

google {
  application-name = "cromwell"
  auths = [{
      name = "application_default"
      scheme = "application_default"
    }]
}


ubuntu@ip-172-31-0-216:~/topmed-workflows/functional-equivalence-wdl$ java -Dconfig.file=/home/ubuntu/cromwell.conf -jar ~/.dockstore/libraries/cromwell-30.1.jar run /home/ubuntu/topmed-workflows/functional-equivalence-wdl/FunctionalEquivalence.wdl -i FunctionalEquivalence.inputs -o FunctionalEquivalence.options
...

[ERROR] [02/12/2018 21:52:10.294] [cromwell-system-akka.dispatchers.backend-dispatcher-124] [akka://cromwell-system/user/SingleWorkflowRunnerActor/WorkflowManagerActor/WorkflowActor-b7008d77-fb37-4785-a95f-6496cffac360/WorkflowExecutionActor-b7008d77-fb37-4785-a95f-6496cffac360/b7008d77-fb37-4785-a95f-6496cffac360-EngineJ
obExecutionActor-PairedEndSingleSampleWorkflow.CreateSequenceGroupingTSV:NA:1/b7008d77-fb37-4785-a95f-6496cffac360-BackendJobExecutionActor-PairedEndSingleSampleWorkflow.CreateSequenceGroupingTSV:NA:1/BackgroundConfigAsyncJobExecutionActor] BackgroundConfigAsyncJobExecutionActor [UUID(b7008d77)PairedEndSingleSampleWorkflo
w.CreateSequenceGroupingTSV:NA:1]: Error attempting to Execute
common.exception.AggregatedMessageException: Error(s):
:
java.lang.IllegalArgumentException: Could not find suitable filesystem among Default to parse gs://broad-references/hg38/v0/Homo_sapiens_assembly38.dict.

**Comment by ruchim** [comment]
I forgot something very important-- my apologies @wshands....
Hopefully this is the final attempt~
#### cromwell.conf
```
include required(classpath("application"))

engine {
  filesystems {
    gcs {
      auth = "application_default"
    }
  }
}

backend.providers.Local.config {
  filesystems {
    gcs {
      auth = "application_default"
    }
  }
}

google {
  application-name = "cromwell"
  auths = [{
      name = "application_default"
      scheme = "application_default"
    }]
}
```

**Comment by wshands** [comment]
Hi @ruchim,
Thanks it is working now but failing with this error:
...
[February 13, 2018 11:46:02 PM UTC] Executing as root@aaa3dc4eeee5 on Linux 4.4.0-1049-aws amd64; OpenJDK 64-Bit Server VM 1.8.0_111-8u111-b14-2~bpo8+1-b14; Version: 4.beta.5
[February 13, 2018 11:46:03 PM UTC] org.broadinstitute.hellbender.tools.walkers.bqsr.BaseRecalibrator done. Elapsed time: 0.01 minutes.
Runtime.totalMemory()=4019716096
***********************************************************************

A USER ERROR has occurred: Couldn't read file. Error was: /home/ubuntu/topmed-workflows/functional-equivalence-wdl/cromwell-executions/PairedEndSingleSampleWorkflow/b40bfbd3-e7c6-4359-b419-71f92ea1a84c/call-SortSampleBam/execution/NA12878_plumbing.aligned.duplicate_marked.sorted.bam with exception: Cannot read non-existent file: /home/ubuntu/topmed-workflows/functional-equivalence-wdl/cromwell-executions/PairedEndSingleSampleWorkflow/b40bfbd3-e7c6-4359-b419-71f92ea1a84c/call-SortSampleBam/execution/NA12878_plumbing.aligned.duplicate_marked.sorted.bam

***********************************************************************

The NA12878_plumbing.aligned.duplicate_marked.sorted.bam file is present at the path listed above and readable by all but is owned by root. Not sure why it cannot be read; perhaps a volume needs to be mounted? ( I am using the options file)

**Comment by wshands** [comment]
Hi @ruchim,
Also it seems at this time Dockstore only allows example test input files to have a 'json' or 'yml' extension so would you change the name of the input file from FunctionalEquivalence.inputs to FunctionalEquivalence.json ? Thanks!

**Comment by ruchim** [comment]
Hey @wshands ,

Is the .options file being stored in Dockstore as well? If yes, is the current extension acceptable?

**Comment by wshands** [comment]
Hi @ruchim,
Good catch; Dockstore cannot accommodate the .options file.

**Comment by wshands** [comment]
Hi @ruchim,
Any idea how I can fix the following error mentioned above? A USER ERROR has occurred: Couldn't read file. Error was: /home/ubuntu/topmed-workflows/functional-equivalence-wdl/cromwell-executions/PairedEndSingleSampleWorkflow/b40bfbd3-e7c6-4359-b419-71f92ea1a84c/call-SortSampleBam/execution/NA12878_plumbing.aligned.duplicate_marked.sorted.bam with exception: Cannot read non-existent file: /home/ubuntu/topmed-workflows/functional-equivalence-wdl/cromwell-executions/PairedEndSingleSampleWorkflow/b40bfbd3-e7c6-4359-b419-71f92ea1a84c/call-SortSampleBam/execution/NA12878_plumbing.aligned.duplicate_marked.sorted.bam

**Comment by ruchim** [comment]
@wshands I've made a PR to make the WDL workflow files compatible with Dockstore.

In terms of debugging the any WDL failures,  one of the best places to start is checking on the content of the *-stderr.log/*-stderr.log files of the execution directory where output wasn't properly created. In this case, it would be helpful to check the contents of `/home/ubuntu/topmed-workflows/functional-equivalence-wdl/cromwell-executions/PairedEndSingleSampleWorkflow/b40bfbd3-e7c6-4359-b419-71f92ea1a84c/call-SortSampleBam/execution/SortSampleBam-stderr.log`.
