### ISSUE TITLE
CWL implementation of TopMed alignment workflow

### ISSUE THREAD

**Issue by wshands** [DataBiosphere/topmed-workflows#4]
Alignment
pipeline standard:
https://github.com/CCDG/Pipeline-Standardization/blob/master/PipelineStandard.md
Implementations:
https://github.com/DataBiosphere/topmed-workflows/tree/master/functional-equivalence-wdl (Broad Institute)

(U of Chicago is currently working on a CWL implementation)

┆Issue is synchronized with this [JIRA Task](https://ucsc-cgl.atlassian.net/browse/TOP-4)
┆Issue Number: TOP-4

**Comment by cricketsloan** [comment]
We believe that SevenBridges and UChicago are both thinking about making the CWL workflows for TOPmed with using Goncalo's specs.

Please put the point person for UChicago here.

Please put the point person at Xenon here.

The task here is to make a clean hand off.

**Comment by cricketsloan** [comment]
➤ Walt Shands commented:

Yilin Xu at U of Chicago has implemented the CWL version of the Broad's Functionally Equivalent alignment workflow.

https://github.com/uc-cdis/topmed-cwl

https://dockstore.org/workflows/github.com/uc-cdis/topmed-cwl/functional_equivalent_cwl
