### ISSUE TITLE
replace current checker logic with GATK variant-caller checker in our WDL VCF topmed-variantcaller-checker.wdl

### ISSUE THREAD

**Issue by cricketsloan** [DataBiosphere/topmed-workflows#44]
In our [WDL workflow](https://github.com/DataBiosphere/topmed-workflows/releases/tag/1.13.0) that determines the variant overlap between two VCFs processed by the variant calling workflow, replace the current logic with Francisco's VCF comparator that is based on the [CCDG pipeline standard](https://github.com/CCDG/Pipeline-Standardization/blob/master/PipelineStandard.md) and uses the [GATK Genotype Concordance checker](https://software.broadinstitute.org/gatk/documentation/tooldocs/3.8-0/org_broadinstitute_gatk_tools_walkers_variantutils_GenotypeConcordance.php).

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/TOP-23)
┆Issue Number: TOP-23
┆Epic: Epic 2: Workflows

**Comment by mjkrause** [comment]
This refers to #48. Closing it.

**Comment by cricketsloan** [comment]
➤ Michael Krause commented:

Although this issue has been closed, the process of testing workflow code needs to be revised. The way it is practiced for the VCF checker code lacks robustness and generality. The main points to find solutions for are:

  * how to use the reference data (e.g., hg38) in tests without the need to download the entire reference folder 
  * how to run a the actual workflow in a test
